FROM ubuntu

MAINTAINER fabricekra (krafabrice64@gmail.com)


RUN apt-get update


RUN apt-get install -y nginx

RUN  apt-get install -y git && \
    apt-get clean


EXPOSE 80


#ADD static-website-example-master/ /var/www/html/

RUN rm -Rf /var/www/html/*

RUN git clone https://github.com/cloudacademy/static-website-example.git /var/www/html/


ENTRYPOINT [ "usr/sbin/nginx", "-g", "daemon off;" ]