apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: {{ .Values.certificate.issuer }}
spec:
  acme:
    server: {{ if eq .Values.certificate.issuer "letsencrypt-staging" }}https://acme-staging-v02.api.letsencrypt.org/directory{{ else }}https://acme-v02.api.letsencrypt.org/directory{{ end }}
    email: {{ .Values.letsencrypt.email }}
    privateKeySecretRef:
      name: {{ .Values.certificate.issuer }}
    solvers:
      - http01:
          ingress:
            class: {{ .Values.ingress.className }}