apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.app.name }}-ingress
  namespace: {{ .Values.app.namespace }}
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.certificate.issuer }}
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: "{{ $value }}"
    {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.domains.primary }}
      http:
        paths:
          - path: {{ .Values.services.gateway.path }}
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.services.gateway.name }}
                port:
                  number: {{ .Values.services.gateway.port }}
    {{- range .Values.domains.aliases }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $.Values.services.gateway.name }}
                port:
                  number: {{ $.Values.services.gateway.port }}
    {{- end }}
  tls:
    - hosts:
        - {{ .Values.domains.primary }}
        {{- range .Values.domains.aliases }}
        - {{ . }}
        {{- end }}
      secretName: {{ .Values.certificate.secretName }}