apiVersion: v1
kind: Service
metadata:
  name: gateway-service
  namespace: {{ .Values.namespace }}
  labels:
    app: gateway-service
    chart: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: gateway-service
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
