apiVersion: v2
name: gateway-service
description: API Gateway - Central entry point for microservices
type: application
version: 1.0.0
appVersion: "1.0.0"

# Dépendances locales (optionnel : ne mets ça que si tu utilises des subcharts)
#dependencies:
#  - name: users-service
#    version: "1.0.0"
#    repository: "file://../users-service"
#    condition: users-service.enabled
#  - name: products-service
#    version: "1.0.0"
#    repository: "file://../products-service"
#    condition: products-service.enabled
#  - name: orders-service
#    version: "1.0.0"
#    repository: "file://../orders-service"
#    condition: orders-service.enabled
