namespace: microservices

image:
  repository: fabrice28/users_service

  tag: "24"
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 8001

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

readinessProbe:
  httpGet:
    path: /
    port: 8001
  initialDelaySeconds: 10
  periodSeconds: 5
