namespace: microservices

image:
  repository: fabrice28/orders_service
  tag: "3"
  pullPolicy: Always

replicaCount: 1

service:
  type: ClusterIP
  port: 8003

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "512Mi"
    cpu: "500m"

readinessProbe:
  httpGet:
    path: /
    port: 8003
  initialDelaySeconds: 10
  periodSeconds: 5
