namespace: microservices   # Namespace où le service existe et où l'ingress sera créé

ingress:
  enabled: true
  className: nginx
  hosts:
    - host: myapp.local
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - myapp.local
      secretName: my-tls-secret
  forceSSLRedirect: true

service:
  name: gateway-service
  port: 8000
