# Configuration de l'application
app:
  name: "crud-app"
  namespace: "microservices"

# Domaines et certificats
domains:
  primary: "crud-app.com"  # ← À changer pour votre domaine réel
  aliases:
    - "www.crud-app.com"

# Configuration des services
services:
  gateway:
    name: "gateway-service"
    port: 8000
    path: "/"

# Configuration des certificats
certificate:
  secretName: "crud-app-tls"
  issuer: "letsencrypt-staging"  # Staging pour test, puis "letsencrypt-prod"

# Email pour Let's Encrypt (OBLIGATOIRE)
letsencrypt:
  email: "krafabrice64@gmail.com"  # ← REMPLACER par votre vrai email

# Configuration Ingress
ingress:
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"